ALTER TABLE cash_cuts
ADD COLUMN IF NOT EXISTS fondo_inicial NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS monto_esperado NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS monto_real NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS diferencia NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS nombre_cajero TEXT;
